spring:
    application:
        name: auth

    datasource:
        url: jdbc:postgresql://localhost:5432/school
        username: louis
        password: password
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            format_sql: true

server:
    port: 8083

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true