# Secrets for testing purposes only

server:
    port: 0

spring:
    application:
        name: student
    data:
        mongodb:
            host: localhost
            port: 27017
            database: local
            auto-index-creation: true

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true